## YAML Template.
---
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kuzola_bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

